# FAISS Clustering Configuration

# Data settings
data:
  use_synthetic: false                # Set to false to use existing parquet files
  n_vectors: 100000                   # Only used if use_synthetic is true
  n_dimensions: 90                    # Only used if use_synthetic is true
  data_path: "data/synthetic"         # Directory containing parquet files
  embedding_columns: null             # Set to null to auto-detect, or specify list of column names
  normalize_vectors: false            # Set to false if vectors are already normalized
  batch_size: 50000                   # Batch size for loading large datasets

# Clustering settings
clustering:
  n_clusters: 500                     # Number of clusters to create
  use_pq: false                       # Whether to use Product Quantization
  pq_m: 8                             # Number of sub-quantizers for PQ (if used)
  pq_bits: 8                          # Bits per sub-quantizer (usually 8 for 256 centroids)
  nprobe: 1                           # Number of clusters to search during query
  verbose: true                       # Show detailed output
  gpu: true                          # Use GPU if available

# Training settings
training:
  n_iterations: 20                    # Training iterations for k-means
  sample_size: 1000000                # Max vectors to use for training (set to -1 to use all)
  seed: 42                            # Random seed for reproducibility

# Output settings
output:
  save_codebook: true                 # Save the codebook (centroids)
  save_index: true                    # Save the entire index
  save_assignments: true              # Save cluster assignments for input vectors
  output_dir: "results/clustering"    # Directory to save results
  codebook_file: "codebook.npy"       # Filename for codebook
  index_file: "faiss_index"           # Filename for FAISS index
  assignments_file: "assignments.npy" # Filename for cluster assignments

# Query settings
query:
  run_query_examples: true            # Run example queries after clustering
  n_query_examples: 5                 # Number of example queries to run
  k: 5                                # Number of nearest neighbors to retrieve