# Configuration for synthetic data generation

# Data generation settings
data:
  n_vectors: 1000000              # Number of vectors to generate
  n_dimensions: 90                # Dimensions of each embedding vector
  batch_size: 1000000              # Number of vectors per batch/file
  normalize_vectors: true         # Whether to normalize vectors to unit length
  seed: 42                        # Random seed for reproducibility

# Output settings
output:
  output_dir: "data/synthetic"    # Directory to save the generated parquet files
  file_prefix: "embeddings_batch" # Prefix for the parquet files